name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 16.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install

    - name: Build Frontend
      run: yarn build && ls -lah

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

#    - name: Login to DockerHub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: List Dir
      run: ls -lah

    - name: Build and Push Image
      uses: docker/build-push-action@v3
      with:
#        push: true
        context: .
        tags: ccaspanello/todo-frontend:latest