name: Release

on:
  workflow_dispatch:
    inputs:
      nextSnapshotVersion:
        description: 'Next SNAPSHOT Version (ie, 1.0.1-SNAPSHOT)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Log Inputs
      run: |
        echo "Next SNAPSHOT Version: ${{ github.event.inputs.nextSnapshotVersion }}"

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 16.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0
        cache: 'yarn'

    - name: Roll Version
      run: |
        releaseVersion=$(node -e "console.log(require('./package.json').version.replace('-SNAPSHOT',''));")
        yarn version --new-version $releaseVersion
        git config --global user.name 'Service Account'
        git config --global user.email 'ccaspanello@gmail.com'
        git add package.json
        git commit -am "[RELEASE] Setting release version to: $releaseVersion"
        git push
        yarn version --new-version ${{ github.event.inputs.nextSnapshotVersion }}
        git add package.json
        git commit -am "[RELEASE] Setting SNAPSHOT version to: $releaseVersion"
