name: Release

on:
  workflow_dispatch:
    inputs:
      nextSnapshotVersion:
        description: 'Next SNAPSHOT Version (ie, 1.0.1-SNAPSHOT)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Log Inputs
      run: |
        echo "Next SNAPSHOT Version: ${{ github.event.inputs.nextSnapshotVersion }}"

    - name: Checkout Code
      uses: actions/checkout@v3
